print("EX3.a")
print("D is 'people'")
print("P is 'are blond'")
print("Q is 'are westerners'")
print("\nFormal form: For all x in D, P(x) then Q(x)")

print("\nEX3.b")
print("D is 'a person'")
print("P is 'hair is black'")
print("Q is 'are westerners'")
print("\nFormal form: Exist x in D, P(x) then Q(x)")

print("\nEX3.c")
print("D is students")
print("P is study correctly")
print("Q is have high score")
print("\nFormal form: For all x in D, P(x) then Q(x)")

print("\nEX3.d")
print("D is mammal")
print("P is live in the sea")
print("Q is are either dolphins or whales")
print("\nFormal form: For all x in D, P(x) then Q(x)")

print("\nEX3.e")
print("D is bird")
print("P is don't have wings and can swim")
print("Q is are penguins")
print("\nFormal form: For all x in D, P(x) then Q(x)")

print("\nEX3.f")
print("D is bird")
print("P is have wing")
print("Q is can't fly")
print("\nFormal form: Exist x in D, P(x) then Q(x)")
